### ISSUE TITLE
Can not open chrome custom tab

### ISSUE THREAD

**Issue by takahirom** [DroidKaigi/conference-app-2021#444]
**Overview (Required)**
- When you open chrome  custom  tab, the app is crash

**Steps To Reproduce**

1. Go to 'news'
2. Click on 'news'

**Expected behavior**
If it's clear
Open chrome  custom  tabs

**Screenshots**
If applicable

**Env:**
 - Device: Pixel3
 - OS: 12 beta 1
 - App Version or the branch main

**Additional context**
Any other notes

**Comment by takahirom** [comment]
Stacktrace

```
2021-06-30 09:54:08.078 16516-16516/io.github.droidkaigi.feeder.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.droidkaigi.feeder.debug, PID: 16516
    java.lang.IllegalArgumentException: Navigation destination that matches request NavDeepLinkRequest{ uri=android-app://androidx.navigation.chrome/chrome/https://droidkaigi.jp/fm/episode/6 } cannot be found in the navigation graph NavGraph(0x0) startDestination={Destination(0x557bc55d) route=feed/{feedTab}}
        at androidx.navigation.NavController.navigate(NavController.kt:1319)
        at androidx.navigation.NavController.navigate(NavController.kt:1285)
        at io.github.droidkaigi.feeder.core.navigation.NavHostControllerKt.navigateChromeCustomTabs(NavHostController.kt:44)
        at io.github.droidkaigi.feeder.core.navigation.NavHostControllerKt.navigateChromeCustomTabs$default(NavHostController.kt:40)
        at io.github.droidkaigi.feeder.AppActions$showChromeCustomTabs$1.invoke(AppContent.kt:179)
        at io.github.droidkaigi.feeder.AppActions$showChromeCustomTabs$1.invoke(AppContent.kt:178)
        at io.github.droidkaigi.feeder.AppContentKt$AppContent$3$1$1$3$2$1.invoke(AppContent.kt:110)
        at io.github.droidkaigi.feeder.AppContentKt$AppContent$3$1$1$3$2$1.invoke(AppContent.kt:109)
        at io.github.droidkaigi.feeder.feed.FirstFeedItemKt$FirstFeedItem$1.invoke(FirstFeedItem.kt:45)
        at io.github.droidkaigi.feeder.feed.FirstFeedItemKt$FirstFeedItem$1.invoke(FirstFeedItem.kt:45)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:134)
        at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:134)
        at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:378)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:167)
        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:372)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:406)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:398)
        at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:303)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:431)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:328)
        at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:341)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:287)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
        at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:151)
        at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:90)
        at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:77)
        at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:804)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
2021-06-30 09:54:08.079 16516-16516/io.github.droidkaigi.feeder.debug E/AndroidRuntime:     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:502)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1890)
        at android.app.Activity.dispatchTouchEvent(Activity.java:4181)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:460)
        at android.view.View.dispatchPointerEvent(View.java:14762)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6265)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6066)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5544)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5601)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5567)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5732)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5575)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5789)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5601)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5567)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5575)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5548)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8447)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8398)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:8367)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8570)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:259)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:335)
        at android.os.Looper.loopOnce(Looper.java:161)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7796)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
    
    
```

**Comment by takahirom** [comment]
The cause seems to be that the following regular expressions inside Navigation do not match. 👀 
`"result:"+pattern!!.matcher(deepLink.toString()).matches() +" pattern:"+ pattern.toString() + " deepLink:"+deepLink.toString()`
↓

```
result:false 
pattern:^\Qandroid-app://androidx.navigation.chrome/chrome/\E([^/]+?)($|(\?(.)*)) 
deepLink:android-app://androidx.navigation.chrome/chrome/https://droidkaigi.jp/fm/episode/6
```

![image](https://user-images.githubusercontent.com/1386930/123887403-63538980-d98c-11eb-8e75-437f13478f4c.png)

![image](https://user-images.githubusercontent.com/1386930/123887346-50d95000-d98c-11eb-943f-d526548782f7.png)

Proably `([^/]+?)($|(\?(.)*))` is not matched `https://droidkaigi.jp/fm/episode/6`
But I can not understand this `([^/]+?)($|(\?(.)*))` 😭 
![image](https://user-images.githubusercontent.com/1386930/123887695-effe4780-d98c-11eb-896e-ebfec48bcfb3.png)
![image](https://user-images.githubusercontent.com/1386930/123888005-892d5e00-d98d-11eb-8f12-e762251f47e1.png)

**Comment by yshrsmz** [comment]
`([^/]+?)` means "string containing any char but `/`", so you cannot include `/` char.
`($|(\?(.)*))` basically means "either end-of-string char or query-parameter-like string"

So I think your last example should match.

I wonder what that last 'circle char' in your screenshot means 🤔  Can you remove that? or is it a part of the pattern?


<img width="486" alt="スクリーンショット 2021-06-30 11 02 00" src="https://user-images.githubusercontent.com/654889/123891151-6ef67e80-d993-11eb-8d66-310b30ac59be.png">

<img width="446" alt="スクリーンショット 2021-06-30 11 08 48" src="https://user-images.githubusercontent.com/654889/123891283-a9601b80-d993-11eb-837f-625465ad9924.png">
